import {storage,uid} from './storage.js';
import {VoiceEngine} from './voice.js';
import {Waveform} from './waveform.js';
import {localIntent,aiChat} from './brain.js';
import {notify} from './tools.js';
import {CONNECTORS} from './index.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const els={messages:$('#messages'),input:$('#promptInput'),statusText:$('#statusText'),statusDot:$('#statusDot'),stateKicker:$('#stateKicker'),stateDetail:$('#stateDetail'),micButton:$('#micButton'),micHint:$('#micHint'),drawer:$('#drawer'),drawerContent:$('#drawerContent'),drawerTitle:$('#drawerTitle'),toast:$('#toast'),app:$('#app'),clock:$('#clock'),actionRail:$('#actionRail')};
let settings=storage.settings;let activeChat=null;let waveform=new Waveform($('#waveCanvas'));let audioCtx=null;let micStream=null;
const voice=new VoiceEngine({onTranscript:handleTranscript,onState:setVisualState});

function ensureChat(){if(activeChat)return activeChat;const saved=storage.activeChat;if(saved){activeChat=storage.chats.find(c=>c.id===saved)||null;}if(!activeChat){activeChat={id:uid('chat'),title:'Nouvelle conversation',createdAt:Date.now(),updatedAt:Date.now(),messages:[]};storage.chats=[activeChat,...storage.chats];storage.activeChat=activeChat.id;}return activeChat;}
function saveChat(){activeChat.updatedAt=Date.now();storage.activeChat=activeChat.id;storage.chats=storage.chats.map(c=>c.id===activeChat.id?activeChat:c);}
function escapeHTML(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function renderMessage(m){const wrap=document.createElement('div');wrap.className=`message ${m.role}`;wrap.innerHTML=`<div class="meta"><strong>${m.role==='user'?'VOUS':'GENIS'}</strong>${m.meta?.tool?`<span>· ${escapeHTML(m.meta.tool)}</span>`:''}</div><div class="bubble">${escapeHTML(m.content)}</div>`;els.messages.appendChild(wrap);els.messages.scrollTop=els.messages.scrollHeight;}
function renderChat(){ensureChat();els.messages.innerHTML='';if(!activeChat.messages.length){els.messages.innerHTML=`<div class="welcome"><strong>GENIS</strong><p>Je peux exécuter des actions locales, orchestrer des outils et utiliser une passerelle IA quand elle est configurée.</p><div class="suggestions"><button class="suggestion" data-suggest="Mets un minuteur de 10 minutes">Minuteur</button><button class="suggestion" data-suggest="Quelle est la météo ?">Météo</button><button class="suggestion" data-suggest="Mémorise que je préfère les réponses courtes">Mémoire</button><button class="suggestion" data-suggest="Ouvre Deezer">Deezer</button></div></div>`;}else activeChat.messages.forEach(renderMessage);}
function addMessage(role,content,meta={}){ensureChat();const m={id:uid('msg'),role,content,meta,createdAt:Date.now()};activeChat.messages.push(m);if(role==='user'&&activeChat.title==='Nouvelle conversation')activeChat.title=content.slice(0,44);saveChat();renderMessage(m);return m;}
function setVisualState(state,detail){const map={idle:['VEILLE','Je suis prête.'],listening:['ÉCOUTE','Je vous écoute.'],thinking:['TRAITEMENT','J’analyse la demande.'],speaking:['RÉPONSE','GENIS parle.'],error:['ERREUR',detail||'Une erreur est survenue.']};const [k,d]=map[state]||map.idle;els.stateKicker.textContent=k;els.stateDetail.textContent=detail||d;els.statusText.textContent=state==='listening'?'Écoute':state==='thinking'?'Traitement':state==='speaking'?'Réponse':state==='error'?'Erreur':'Prête';els.statusDot.className=`status-dot ${state==='error'?'error':state==='idle'?'':'busy'}`;waveform.setState(state==='listening'?'listening':state==='speaking'?'speaking':state==='thinking'?'thinking':'idle');}
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),2200)}

async function enableMic(){
 if(!voice.supported()){toast('La reconnaissance vocale du navigateur n’est pas disponible.');return;}
 try{
   if(!micStream){micStream=await navigator.mediaDevices.getUserMedia({audio:true});audioCtx=new (window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaStreamSource(micStream);const an=audioCtx.createAnalyser();an.fftSize=128;src.connect(an);waveform.attachAnalyser(an);}
   settings.micEnabled=true;storage.settings=settings;els.micButton.setAttribute('aria-pressed','true');els.micHint.textContent='Micro actif';voice.start();
 }catch{toast('Le microphone est bloqué. Vérifiez l’autorisation du navigateur.');}
}
function disableMic(){voice.stop();micStream?.getTracks().forEach(t=>t.stop());micStream=null;settings.micEnabled=false;storage.settings=settings;els.micButton.setAttribute('aria-pressed','false');els.micHint.textContent='Micro désactivé';setVisualState('idle');}
function handleTranscript({finalText,interimText}){if(interimText){els.stateDetail.textContent=interimText;waveform.setLevel(Math.min(1,0.15+interimText.length/80));}if(finalText){els.input.value=finalText;sendPrompt(finalText,true);}}

async function sendPrompt(text,fromVoice=false){
 text=text.trim();if(!text)return;addMessage('user',text);els.input.value='';els.input.style.height='44px';setVisualState('thinking');
 let result=null;
 try{for(const a of getAutomationMatches(text)) await executeAutomation(a);result=await localIntent(text,{chat:activeChat});if(!result){const ai=await aiChat(text,activeChat.messages);result=ai||{text:'Je n’ai pas encore de connecteur pour cette action. Je peux néanmoins l’ouvrir, préparer une recherche ou gérer les fonctions locales. Consultez Applications pour voir les capacités disponibles.'};} addMessage('assistant',result.text,result.meta||{});setVisualState('speaking');if(settings.voiceEnabled)voice.speak(result.text,{rate:settings.speechRate,volume:settings.volume,onEnd:()=>setVisualState('idle')});else setVisualState('idle');}
 catch(e){addMessage('assistant',`Je n’ai pas pu terminer cette action : ${e.message||e}`,{error:true});setVisualState('error',e.message);toast('Action interrompue');}
}
function getAutomationMatches(text){return storage.automations.filter(a=>a.enabled&&text.toLowerCase().includes(a.trigger.toLowerCase()));}
async function executeAutomation(a){for(const action of a.actions||[]){if(action.kind==='say')addMessage('assistant',action.value,{tool:'automation'});if(action.kind==='open'){window.open(action.value,'_blank','noopener');}if(action.kind==='timer'){const mins=Number(action.value);if(mins)await localIntent(`Mets un minuteur de ${mins} minutes`);}}a.lastRun=Date.now();storage.automations=storage.automations;}

function openDrawer(panel){els.drawer.classList.add('open');els.drawer.setAttribute('aria-hidden','false');renderDrawer(panel);}
function closeDrawer(){els.drawer.classList.remove('open');els.drawer.setAttribute('aria-hidden','true');}
function renderDrawer(panel){const title={history:'Conversations',apps:'Applications',memory:'Mémoire',tasks:'Tâches',notifications:'Notifications',settings:'Réglages'}[panel]||'Accueil';els.drawerTitle.textContent=title;els.drawerContent.innerHTML=drawerMarkup(panel);bindDrawer();}
function drawerMarkup(panel){
 if(panel==='history')return `<div class="setting-group"><div class="setting-title">Historique</div>${storage.chats.length?storage.chats.slice(0,25).map(c=>`<div class="list-card"><strong>${escapeHTML(c.title)}</strong><small>${new Date(c.updatedAt).toLocaleString('fr-FR')}</small><div class="list-actions"><button class="secondary-btn" data-load-chat="${c.id}">Ouvrir</button><button class="secondary-btn danger-btn" data-delete-chat="${c.id}">Supprimer</button></div></div>`).join(''):'<div class="list-card"><small>Aucune conversation enregistrée.</small></div>'}</div>`;
 if(panel==='memory')return `<div class="setting-group"><div class="setting-title">Mémoire autorisée</div><div class="list-card"><small>Les souvenirs ci-dessous sont stockés uniquement dans ce navigateur. Vous pouvez les modifier ou les supprimer.</small></div>${storage.memories.length?storage.memories.map(m=>`<div class="list-card"><strong>${escapeHTML(m.text)}</strong><small>${new Date(m.createdAt).toLocaleString('fr-FR')}</small><div class="list-actions"><button class="secondary-btn danger-btn" data-delete-memory="${m.id}">Supprimer</button></div></div>`).join(''):'<div class="list-card"><small>Rien de mémorisé.</small></div>'}</div><div class="setting-group"><div class="setting-title">Ajouter</div><div class="setting-row"><div class="field-stack"><label>Souvenir</label><input id="newMemory" class="input" placeholder="Ex. Je préfère les réponses courtes"></div><button class="secondary-btn" data-add-memory>Ajouter</button></div></div>`;
 if(panel==='apps'){return `<div class="setting-group"><div class="setting-title">Connecteurs</div>${CONNECTORS.map(c=>`<div class="setting-row"><div class="setting-main"><strong>${escapeHTML(c.name)} <span class="pill">${escapeHTML(c.status)}</span></strong><small>${escapeHTML(c.kind)} · ${escapeHTML(c.note)}</small></div><button class="secondary-btn" data-open-connector="${c.id}">${c.url?'Ouvrir':'Préparer'}</button></div>`).join('')}</div>`;}
 if(panel==='tasks'){const tasks=storage.tasks.filter(t=>t.status==='running');return `<div class="setting-group"><div class="setting-title">Tâches en cours</div>${tasks.length?tasks.map(t=>{const left=Math.max(0,t.dueAt-Date.now());return `<div class="list-card"><strong>${escapeHTML(t.label)} <span class="pill">${Math.ceil(left/1000)}s</span></strong><small>Minuteur local · ${new Date(t.dueAt).toLocaleTimeString('fr-FR')}</small><div class="list-actions"><button class="secondary-btn danger-btn" data-cancel-task="${t.id}">Annuler</button></div></div>`}).join(''):'<div class="list-card"><small>Aucune tâche en cours.</small></div>'}</div><div class="setting-group"><div class="setting-title">Créer une automatisation</div><div class="setting-row"><div class="field-stack"><label>Phrase déclencheuse</label><input id="autoTrigger" class="input" placeholder="bonne nuit"></div></div><div class="setting-row"><div class="field-stack"><label>Action</label><select id="autoKind" class="input"><option value="say">Répondre</option><option value="open">Ouvrir un service</option><option value="timer">Minuteur</option></select></div></div><div class="setting-row"><div class="field-stack"><label>Valeur</label><input id="autoValue" class="input" placeholder="Ex. Bonne nuit. / Deezer / 10"></div><button class="secondary-btn" data-add-auto>Créer</button></div></div><div class="setting-group"><div class="setting-title">Automatisations existantes</div>${storage.automations.length?storage.automations.map(a=>`<div class="list-card"><strong>« ${escapeHTML(a.trigger)} »</strong><small>${a.actions.map(x=>`${escapeHTML(x.kind)}: ${escapeHTML(String(x.value))}`).join(' · ')} · ${a.enabled?'active':'désactivée'}</small><div class="list-actions"><button class="secondary-btn" data-toggle-auto="${a.id}">${a.enabled?'Désactiver':'Activer'}</button><button class="secondary-btn danger-btn" data-delete-auto="${a.id}">Supprimer</button></div></div>`).join(''):'<div class="list-card"><small>Aucune automatisation locale.</small></div>'}</div>`;}
 if(panel==='notifications'){return `<div class="setting-group"><div class="setting-title">Notifications</div>${storage.notifications.length?storage.notifications.slice(0,30).map(n=>`<div class="list-card"><strong>${escapeHTML(n.title)}</strong><small>${escapeHTML(n.body)} · ${new Date(n.createdAt).toLocaleString('fr-FR')}</small></div>`).join(''):'<div class="list-card"><small>Aucune notification.</small></div>'}</div><div class="setting-group"><div class="setting-title">Permission navigateur</div><div class="setting-row"><div class="setting-main"><strong>Notifications</strong><small>${('Notification' in window) ? Notification.permission : 'non disponible'}</small></div><button class="secondary-btn" data-request-notifications>Autoriser</button></div></div>`;}
 return settingsMarkup();
}
function settingsMarkup(){return `<div class="setting-group"><div class="setting-title">Connexion IA</div><div class="setting-row"><div class="field-stack full"><label>URL de la passerelle</label><input id="gatewayUrl" class="input" value="${escapeHTML(settings.gatewayUrl||'')}" placeholder="https://votre-worker.exemple.workers.dev"></div></div><div class="setting-row"><div class="field-stack full"><label>Mot de passe partagé (facultatif)</label><input id="gatewaySecret" class="input" type="password" value="${escapeHTML(settings.gatewaySecret||'')}"></div></div><div class="setting-row"><div class="field-stack full"><label>Modèle</label><input id="model" class="input" value="${escapeHTML(settings.model||'claude-haiku-4-5-20251001')}"></div></div><div class="setting-row"><button class="secondary-btn" data-save-settings>Enregistrer</button><button class="secondary-btn" data-test-gateway>Tester la connexion</button></div></div><div class="setting-group"><div class="setting-title">Voix & microphone</div><div class="setting-row"><div class="setting-main"><strong>Réponse vocale</strong><small>Utilise la synthèse vocale native du navigateur.</small></div><button class="toggle ${settings.voiceEnabled?'on':''}" data-toggle-setting="voiceEnabled"></button></div><div class="setting-row"><div class="setting-main"><strong>Microphone</strong><small>${voice.supported()?'Reconnaissance vocale disponible':'Reconnaissance vocale non détectée'}</small></div><button class="toggle ${settings.micEnabled?'on':''}" data-toggle-mic></button></div><div class="setting-row"><div class="field-stack"><label>Vitesse</label><input id="speechRate" type="range" min="0.7" max="1.3" step="0.05" value="${settings.speechRate}"></div><span id="speechRateValue">${settings.speechRate}</span></div></div><div class="setting-group"><div class="setting-title">Sécurité & permissions</div>${Object.entries(storage.permissions).map(([k,v])=>`<div class="setting-row"><div class="setting-main"><strong>${escapeHTML(k)}</strong><small>Autoriser cette capacité locale.</small></div><button class="toggle ${v?'on':''}" data-toggle-permission="${k}"></button></div>`).join('')}</div><div class="setting-group"><div class="setting-title">Comptes connectés</div><div class="list-card"><small>Aucun OAuth n’est configuré dans cette version. Les connecteurs affichent leur statut sans prétendre être connectés.</small></div></div><div class="setting-group"><div class="setting-title">Données locales</div><div class="setting-row"><div class="setting-main"><strong>Exporter</strong><small>Crée une sauvegarde JSON de l’état GENIS.</small></div><button class="secondary-btn" data-export>Exporter</button></div><div class="setting-row"><div class="setting-main"><strong>Réinitialiser</strong><small>Efface conversations, mémoire, tâches et réglages.</small></div><button class="secondary-btn danger-btn" data-reset>Réinitialiser</button></div></div>`;}

function bindDrawer(){
 $$('[data-load-chat]').forEach(b=>b.onclick=()=>{activeChat=storage.chats.find(c=>c.id===b.dataset.loadChat)||activeChat;saveChat();renderChat();closeDrawer();});
 $$('[data-delete-chat]').forEach(b=>b.onclick=()=>{storage.chats=storage.chats.filter(c=>c.id!==b.dataset.deleteChat);if(activeChat?.id===b.dataset.deleteChat)activeChat=null;ensureChat();renderChat();renderDrawer('history');});
 $$('[data-delete-memory]').forEach(b=>b.onclick=()=>{storage.memories=storage.memories.filter(m=>m.id!==b.dataset.deleteMemory);renderDrawer('memory');});
 $$('[data-add-memory]').forEach(b=>b.onclick=()=>{const v=$('#newMemory')?.value.trim();if(v){storage.memories=[{id:uid('mem'),text:v,createdAt:Date.now(),source:'manual'},...storage.memories];renderDrawer('memory');toast('Mémoire ajoutée');}});
 $$('[data-open-connector]').forEach(b=>b.onclick=()=>{const c=CONNECTORS.find(x=>x.id===b.dataset.openConnector);if(c.url&&c.url.includes('http'))window.open(c.url,'_blank','noopener');else toast('Connecteur préparé — identifiants/configuration nécessaires.');});
 $$('[data-cancel-task]').forEach(b=>b.onclick=()=>{storage.tasks=storage.tasks.map(t=>t.id===b.dataset.cancelTask?{...t,status:'cancelled'}:t);renderDrawer('tasks');});
 $$('[data-add-auto]').forEach(b=>b.onclick=()=>{const trigger=$('#autoTrigger')?.value.trim();const kind=$('#autoKind')?.value;const value=$('#autoValue')?.value.trim();if(!trigger||!value){toast('Indiquez une phrase et une action.');return;}storage.automations=[{id:uid('auto'),trigger,enabled:true,createdAt:Date.now(),actions:[{kind,value}]} ,...storage.automations];renderDrawer('tasks');toast('Automatisation créée');});
 $$('[data-toggle-auto]').forEach(b=>b.onclick=()=>{storage.automations=storage.automations.map(a=>a.id===b.dataset.toggleAuto?{...a,enabled:!a.enabled}:a);renderDrawer('tasks');});
 $$('[data-delete-auto]').forEach(b=>b.onclick=()=>{storage.automations=storage.automations.filter(a=>a.id!==b.dataset.deleteAuto);renderDrawer('tasks');});
 $$('[data-request-notifications]').forEach(b=>b.onclick=async()=>{if('Notification' in window){const p=await Notification.requestPermission();toast(`Notifications : ${p}`);renderDrawer('notifications');}});
 $$('[data-toggle-setting]').forEach(b=>b.onclick=()=>{settings[b.dataset.toggleSetting]=!settings[b.dataset.toggleSetting];storage.settings=settings;renderDrawer('settings');});
 $$('[data-toggle-mic]').forEach(b=>b.onclick=()=>{closeDrawer();settings.micEnabled?disableMic():enableMic();});
 $$('[data-toggle-permission]').forEach(b=>b.onclick=()=>{const p=storage.permissions;p[b.dataset.togglePermission]=!p[b.dataset.togglePermission];storage.permissions=p;renderDrawer('settings');});
 $('#speechRate')?.addEventListener('input',e=>{settings.speechRate=Number(e.target.value);$('#speechRateValue').textContent=settings.speechRate;storage.settings=settings;});
 $('#gatewayUrl')?.addEventListener('change',e=>settings.gatewayUrl=e.target.value.trim());
 $('#gatewaySecret')?.addEventListener('change',e=>settings.gatewaySecret=e.target.value.trim());
 $('#model')?.addEventListener('change',e=>settings.model=e.target.value.trim());
 $('[data-save-settings]')?.addEventListener('click',()=>{storage.settings=settings;toast('Réglages enregistrés');});
 $('[data-test-gateway]')?.addEventListener('click',async()=>{try{await aiChat('Réponds uniquement par « GENIS OK ».',[]);toast('Passerelle opérationnelle');}catch(e){toast('Échec : '+e.message);}});
 $('[data-export]')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({settings,memories:storage.memories,chats:storage.chats,automations:storage.automations,tasks:storage.tasks,notifications:storage.notifications,permissions:storage.permissions},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='genis-backup.json';a.click();URL.revokeObjectURL(a.href);});
 $('[data-reset]')?.addEventListener('click',()=>{if(confirm('Effacer les données locales de GENIS ?')){localStorage.clear();location.reload();}});
}

$$('.dock-item').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.panel;$$('.dock-item').forEach(x=>x.classList.toggle('active',x===b));if(p==='home'){els.app.classList.remove('show-chat');closeDrawer();}else{els.app.classList.toggle('show-chat',p==='history');openDrawer(p);}}));
$$('[data-close-drawer]').forEach(b=>b.addEventListener('click',closeDrawer));
$('#brandButton').onclick=()=>{$$('.dock-item').forEach(x=>x.classList.toggle('active',x.dataset.panel==='home'));els.app.classList.remove('show-chat');closeDrawer();};
$('#micButton').onclick=()=>settings.micEnabled?disableMic():enableMic();
$('#promptForm').addEventListener('submit',e=>{e.preventDefault();sendPrompt(els.input.value,false)});
els.input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#promptForm').requestSubmit()}});
els.input.addEventListener('input',()=>{els.input.style.height='44px';els.input.style.height=Math.min(150,els.input.scrollHeight)+'px';});
$('#attachButton').onclick=()=>$('#fileInput').click();
$('#fileInput').onchange=()=>{const files=[...$('#fileInput').files];if(files.length)toast(`${files.length} fichier${files.length>1?'s':''} sélectionné${files.length>1?'s':''}.`)};

document.addEventListener('click',e=>{const s=e.target.closest('[data-suggest]');if(s){els.input.value=s.dataset.suggest;sendPrompt(s.dataset.suggest);}});

setInterval(()=>{$('#clock').textContent=new Intl.DateTimeFormat('fr-FR',{hour:'2-digit',minute:'2-digit'}).format(new Date());const now=Date.now();const due=storage.tasks.filter(t=>t.status==='running'&&t.dueAt<=now);if(due.length){storage.tasks=storage.tasks.map(t=>due.some(d=>d.id===t.id)?{...t,status:'done'}:t);due.forEach(t=>{notify('GENIS',t.label+' terminé.');toast(t.label+' terminé.');});}},500);

window.addEventListener('beforeunload',()=>{if(settings.micEnabled)disableMic();});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderChat();setVisualState('idle');
